spring:
  # 数据源配置
  datasource:
    hikari:
      # DB_CLOSE_DELAY：要求最后一个正在连接的连接断开后，不要关闭数据库
      # MODE=MySQL：兼容模式，H2兼容多种数据库，该值可以为：DB2、Derby、HSQLDB、MSSQLServer、MySQL、Oracle、PostgreSQL
      # AUTO_RECONNECT=TRUE：连接丢失后自动重新连接
      # AUTO_SERVER=TRUE：启动自动混合模式，允许开启多个连接，该参数不支持在内存中运行模式
      # TRACE_LEVEL_SYSTEM_OUT、TRACE_LEVEL_FILE：输出跟踪日志到控制台或文件， 取值0为OFF，1为ERROR（默认值），2为INFO，3为DEBUG
      # SET TRACE_MAX_FILE_SIZE mb：设置跟踪日志文件的大小，默认为16M
      # 样例：jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
      jdbc-url: jdbc:h2:~/bil-account;MODE=MySQL
      username: sa
      password: root
      driver-class-name: org.h2.Driver

  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: true
        web-allow-others: true
  sql:
    init:
      # 需要初始化的表结构
      schema-locations:
        - optional:/h2/schema/account.sql
        - optional:/h2/schema/account_flow.sql
        - optional:/h2/schema/account_voucher.sql
        - optional:/h2/schema/account_command.sql
      mode: embedded
      data-locations:
        - optional:/h2/data/init_data.sql

#logging:
#  level:
#    com.bil.account.dao: DEBUG